
-- atribuindo nvarchar para todas colunas para carregar os dados para tabela
CREATE TABLE application_train_staging (
    [SK_ID_CURR] NVARCHAR(MAX), [TARGET] NVARCHAR(MAX), [NAME_CONTRACT_TYPE] NVARCHAR(MAX), [CODE_GENDER] NVARCHAR(MAX), 
    [FLAG_OWN_CAR] NVARCHAR(MAX), [FLAG_OWN_REALTY] NVARCHAR(MAX), [CNT_CHILDREN] NVARCHAR(MAX), [AMT_INCOME_TOTAL] NVARCHAR(MAX), 
    [AMT_CREDIT] NVARCHAR(MAX), [AMT_ANNUITY] NVARCHAR(MAX), [AMT_GOODS_PRICE] NVARCHAR(MAX), [NAME_TYPE_SUITE] NVARCHAR(MAX), 
    [NAME_INCOME_TYPE] NVARCHAR(MAX), [NAME_EDUCATION_TYPE] NVARCHAR(MAX), [NAME_FAMILY_STATUS] NVARCHAR(MAX), [NAME_HOUSING_TYPE] NVARCHAR(MAX), 
    [REGION_POPULATION_RELATIVE] NVARCHAR(MAX), [DAYS_BIRTH] NVARCHAR(MAX), [DAYS_EMPLOYED] NVARCHAR(MAX), [DAYS_REGISTRATION] NVARCHAR(MAX), 
    [DAYS_ID_PUBLISH] NVARCHAR(MAX), [OWN_CAR_AGE] NVARCHAR(MAX), [FLAG_MOBIL] NVARCHAR(MAX), [FLAG_EMP_PHONE] NVARCHAR(MAX), 
    [FLAG_WORK_PHONE] NVARCHAR(MAX), [FLAG_CONT_MOBILE] NVARCHAR(MAX), [FLAG_PHONE] NVARCHAR(MAX), [FLAG_EMAIL] NVARCHAR(MAX), 
    [OCCUPATION_TYPE] NVARCHAR(MAX), [CNT_FAM_MEMBERS] NVARCHAR(MAX), [REGION_RATING_CLIENT] NVARCHAR(MAX), [REGION_RATING_CLIENT_W_CITY] NVARCHAR(MAX), 
    [WEEKDAY_APPR_PROCESS_START] NVARCHAR(MAX), [HOUR_APPR_PROCESS_START] NVARCHAR(MAX), [REG_REGION_NOT_LIVE_REGION] NVARCHAR(MAX), 
    [REG_REGION_NOT_WORK_REGION] NVARCHAR(MAX), [LIVE_REGION_NOT_WORK_REGION] NVARCHAR(MAX), [REG_CITY_NOT_LIVE_CITY] NVARCHAR(MAX), 
    [REG_CITY_NOT_WORK_CITY] NVARCHAR(MAX), [LIVE_CITY_NOT_WORK_CITY] NVARCHAR(MAX), [ORGANIZATION_TYPE] NVARCHAR(MAX), 
    [EXT_SOURCE_1] NVARCHAR(MAX), [EXT_SOURCE_2] NVARCHAR(MAX), [EXT_SOURCE_3] NVARCHAR(MAX), [APARTMENTS_AVG] NVARCHAR(MAX), 
    [BASEMENTAREA_AVG] NVARCHAR(MAX), [YEARS_BEGINEXPLUATATION_AVG] NVARCHAR(MAX), [YEARS_BUILD_AVG] NVARCHAR(MAX), [COMMONAREA_AVG] NVARCHAR(MAX), 
    [ELEVATORS_AVG] NVARCHAR(MAX), [ENTRANCES_AVG] NVARCHAR(MAX), [FLOORSMAX_AVG] NVARCHAR(MAX), [FLOORSMIN_AVG] NVARCHAR(MAX), 
    [LANDAREA_AVG] NVARCHAR(MAX), [LIVINGAPARTMENTS_AVG] NVARCHAR(MAX), [LIVINGAREA_AVG] NVARCHAR(MAX), [NONLIVINGAPARTMENTS_AVG] NVARCHAR(MAX), 
    [NONLIVINGAREA_AVG] NVARCHAR(MAX), [APARTMENTS_MODE] NVARCHAR(MAX), [BASEMENTAREA_MODE] NVARCHAR(MAX), [YEARS_BEGINEXPLUATATION_MODE] NVARCHAR(MAX), 
    [YEARS_BUILD_MODE] NVARCHAR(MAX), [COMMONAREA_MODE] NVARCHAR(MAX), [ELEVATORS_MODE] NVARCHAR(MAX), [ENTRANCES_MODE] NVARCHAR(MAX), 
    [FLOORSMAX_MODE] NVARCHAR(MAX), [FLOORSMIN_MODE] NVARCHAR(MAX), [LANDAREA_MODE] NVARCHAR(MAX), [LIVINGAPARTMENTS_MODE] NVARCHAR(MAX), 
    [LIVINGAREA_MODE] NVARCHAR(MAX), [NONLIVINGAPARTMENTS_MODE] NVARCHAR(MAX), [NONLIVINGAREA_MODE] NVARCHAR(MAX), [APARTMENTS_MEDI] NVARCHAR(MAX), 
    [BASEMENTAREA_MEDI] NVARCHAR(MAX), [YEARS_BEGINEXPLUATATION_MEDI] NVARCHAR(MAX), [YEARS_BUILD_MEDI] NVARCHAR(MAX), [COMMONAREA_MEDI] NVARCHAR(MAX), 
    [ELEVATORS_MEDI] NVARCHAR(MAX), [ENTRANCES_MEDI] NVARCHAR(MAX), [FLOORSMAX_MEDI] NVARCHAR(MAX), [FLOORSMIN_MEDI] NVARCHAR(MAX), 
    [LANDAREA_MEDI] NVARCHAR(MAX), [LIVINGAPARTMENTS_MEDI] NVARCHAR(MAX), [LIVINGAREA_MEDI] NVARCHAR(MAX), [NONLIVINGAPARTMENTS_MEDI] NVARCHAR(MAX), 
    [NONLIVINGAREA_MEDI] NVARCHAR(MAX), [FONDKAPREMONT_MODE] NVARCHAR(MAX), [HOUSETYPE_MODE] NVARCHAR(MAX), [TOTALAREA_MODE] NVARCHAR(MAX), 
    [WALLSMATERIAL_MODE] NVARCHAR(MAX), [EMERGENCYSTATE_MODE] NVARCHAR(MAX), [OBS_30_CNT_SOCIAL_CIRCLE] NVARCHAR(MAX), 
    [DEF_30_CNT_SOCIAL_CIRCLE] NVARCHAR(MAX), [OBS_60_CNT_SOCIAL_CIRCLE] NVARCHAR(MAX), [DEF_60_CNT_SOCIAL_CIRCLE] NVARCHAR(MAX), 
    [DAYS_LAST_PHONE_CHANGE] NVARCHAR(MAX), [FLAG_DOCUMENT_2] NVARCHAR(MAX), [FLAG_DOCUMENT_3] NVARCHAR(MAX), [FLAG_DOCUMENT_4] NVARCHAR(MAX), 
    [FLAG_DOCUMENT_5] NVARCHAR(MAX), [FLAG_DOCUMENT_6] NVARCHAR(MAX), [FLAG_DOCUMENT_7] NVARCHAR(MAX), [FLAG_DOCUMENT_8] NVARCHAR(MAX), 
    [FLAG_DOCUMENT_9] NVARCHAR(MAX), [FLAG_DOCUMENT_10] NVARCHAR(MAX), [FLAG_DOCUMENT_11] NVARCHAR(MAX), [FLAG_DOCUMENT_12] NVARCHAR(MAX), 
    [FLAG_DOCUMENT_13] NVARCHAR(MAX), [FLAG_DOCUMENT_14] NVARCHAR(MAX), [FLAG_DOCUMENT_15] NVARCHAR(MAX), [FLAG_DOCUMENT_16] NVARCHAR(MAX), 
    [FLAG_DOCUMENT_17] NVARCHAR(MAX), [FLAG_DOCUMENT_18] NVARCHAR(MAX), [FLAG_DOCUMENT_19] NVARCHAR(MAX), [FLAG_DOCUMENT_20] NVARCHAR(MAX), 
    [FLAG_DOCUMENT_21] NVARCHAR(MAX), [AMT_REQ_CREDIT_BUREAU_HOUR] NVARCHAR(MAX), [AMT_REQ_CREDIT_BUREAU_DAY] NVARCHAR(MAX), 
    [AMT_REQ_CREDIT_BUREAU_WEEK] NVARCHAR(MAX), [AMT_REQ_CREDIT_BUREAU_MON] NVARCHAR(MAX), [AMT_REQ_CREDIT_BUREAU_QRT] NVARCHAR(MAX), 
    [AMT_REQ_CREDIT_BUREAU_YEAR] NVARCHAR(MAX)
);
BULK INSERT application_train_staging
FROM 'D:\bd\Risco de Credito\home-credit-default-risk\application_train.csv'
WITH (
    FORMAT = 'CSV',
    FIELDQUOTE = '"',        -- Isso impede a "invasão" de colunas
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a',  -- Ou '\n' conforme funcionou antes
    TABLOCK
    );
    -- criando a tabela final atribuindo os tipos de dados corretos
CREATE TABLE application_train_final (
    SK_ID_CURR INT PRIMARY KEY, TARGET INT, NAME_CONTRACT_TYPE NVARCHAR(50), CODE_GENDER NVARCHAR(5),
    FLAG_OWN_CAR NVARCHAR(1), FLAG_OWN_REALTY NVARCHAR(1), CNT_CHILDREN INT, AMT_INCOME_TOTAL FLOAT, 
    AMT_CREDIT FLOAT, AMT_ANNUITY FLOAT, AMT_GOODS_PRICE FLOAT, NAME_TYPE_SUITE NVARCHAR(50), 
    NAME_INCOME_TYPE NVARCHAR(100), NAME_EDUCATION_TYPE NVARCHAR(100), NAME_FAMILY_STATUS NVARCHAR(100),
    NAME_HOUSING_TYPE NVARCHAR(100), REGION_POPULATION_RELATIVE FLOAT, DAYS_BIRTH INT, DAYS_EMPLOYED INT,
    DAYS_REGISTRATION FLOAT, DAYS_ID_PUBLISH INT, OWN_CAR_AGE FLOAT, FLAG_MOBIL INT, FLAG_EMP_PHONE INT, 
    FLAG_WORK_PHONE INT, FLAG_CONT_MOBILE INT, FLAG_PHONE INT, FLAG_EMAIL INT, OCCUPATION_TYPE NVARCHAR(100),
    CNT_FAM_MEMBERS FLOAT, REGION_RATING_CLIENT INT, REGION_RATING_CLIENT_W_CITY INT, 
    WEEKDAY_APPR_PROCESS_START NVARCHAR(20), HOUR_APPR_PROCESS_START INT, REG_REGION_NOT_LIVE_REGION INT,
    REG_REGION_NOT_WORK_REGION INT, LIVE_REGION_NOT_WORK_REGION INT, REG_CITY_NOT_LIVE_CITY INT, 
    REG_CITY_NOT_WORK_CITY INT, LIVE_CITY_NOT_WORK_CITY INT, ORGANIZATION_TYPE NVARCHAR(100),
    EXT_SOURCE_1 FLOAT, EXT_SOURCE_2 FLOAT, EXT_SOURCE_3 FLOAT, APARTMENTS_AVG FLOAT, BASEMENTAREA_AVG FLOAT, 
    YEARS_BEGINEXPLUATATION_AVG FLOAT, YEARS_BUILD_AVG FLOAT, COMMONAREA_AVG FLOAT, ELEVATORS_AVG FLOAT, 
    ENTRANCES_AVG FLOAT, FLOORSMAX_AVG FLOAT, FLOORSMIN_AVG FLOAT, LANDAREA_AVG FLOAT, LIVINGAPARTMENTS_AVG FLOAT,
    LIVINGAREA_AVG FLOAT, NONLIVINGAPARTMENTS_AVG FLOAT, NONLIVINGAREA_AVG FLOAT, APARTMENTS_MODE FLOAT,
    BASEMENTAREA_MODE FLOAT, YEARS_BEGINEXPLUATATION_MODE FLOAT, YEARS_BUILD_MODE FLOAT, COMMONAREA_MODE FLOAT, 
    ELEVATORS_MODE FLOAT, ENTRANCES_MODE FLOAT, FLOORSMAX_MODE FLOAT, FLOORSMIN_MODE FLOAT, LANDAREA_MODE FLOAT,
    LIVINGAPARTMENTS_MODE FLOAT, LIVINGAREA_MODE FLOAT, NONLIVINGAPARTMENTS_MODE FLOAT, NONLIVINGAREA_MODE FLOAT,
    APARTMENTS_MEDI FLOAT, BASEMENTAREA_MEDI FLOAT, YEARS_BEGINEXPLUATATION_MEDI FLOAT, YEARS_BUILD_MEDI FLOAT, 
    COMMONAREA_MEDI FLOAT, ELEVATORS_MEDI FLOAT, ENTRANCES_MEDI FLOAT, FLOORSMAX_MEDI FLOAT, FLOORSMIN_MEDI FLOAT,
    LANDAREA_MEDI FLOAT, LIVINGAPARTMENTS_MEDI FLOAT, LIVINGAREA_MEDI FLOAT, NONLIVINGAPARTMENTS_MEDI FLOAT, 
    NONLIVINGAREA_MEDI FLOAT, FONDKAPREMONT_MODE NVARCHAR(100), HOUSETYPE_MODE NVARCHAR(100), TOTALAREA_MODE FLOAT,
    WALLSMATERIAL_MODE NVARCHAR(100), EMERGENCYSTATE_MODE NVARCHAR(5), OBS_30_CNT_SOCIAL_CIRCLE FLOAT, 
    DEF_30_CNT_SOCIAL_CIRCLE FLOAT, OBS_60_CNT_SOCIAL_CIRCLE FLOAT, DEF_60_CNT_SOCIAL_CIRCLE FLOAT,
    DAYS_LAST_PHONE_CHANGE FLOAT, FLAG_DOCUMENT_2 INT, FLAG_DOCUMENT_3 INT, FLAG_DOCUMENT_4 INT,
    FLAG_DOCUMENT_5 INT, FLAG_DOCUMENT_6 INT, FLAG_DOCUMENT_7 INT, FLAG_DOCUMENT_8 INT, FLAG_DOCUMENT_9 INT,
    FLAG_DOCUMENT_10 INT, FLAG_DOCUMENT_11 INT, FLAG_DOCUMENT_12 INT, FLAG_DOCUMENT_13 INT, FLAG_DOCUMENT_14 INT, 
    FLAG_DOCUMENT_15 INT, FLAG_DOCUMENT_16 INT, FLAG_DOCUMENT_17 INT, FLAG_DOCUMENT_18 INT, FLAG_DOCUMENT_19 INT, 
    FLAG_DOCUMENT_20 INT, FLAG_DOCUMENT_21 INT, AMT_REQ_CREDIT_BUREAU_HOUR FLOAT, AMT_REQ_CREDIT_BUREAU_DAY FLOAT,
    AMT_REQ_CREDIT_BUREAU_WEEK FLOAT, AMT_REQ_CREDIT_BUREAU_MON FLOAT, AMT_REQ_CREDIT_BUREAU_QRT FLOAT, 
    AMT_REQ_CREDIT_BUREAU_YEAR FLOAT
);

--carregando os dados para tabela final com os tipos de dados alterados.
INSERT INTO application_train_final
SELECT 
    TRY_CAST(SK_ID_CURR AS INT), TRY_CAST(TARGET AS INT), NAME_CONTRACT_TYPE, CODE_GENDER, FLAG_OWN_CAR,
    FLAG_OWN_REALTY, TRY_CAST(CNT_CHILDREN AS INT), TRY_CAST(AMT_INCOME_TOTAL AS FLOAT),
    TRY_CAST(AMT_CREDIT AS FLOAT), TRY_CAST(AMT_ANNUITY AS FLOAT), TRY_CAST(AMT_GOODS_PRICE AS FLOAT),
    NAME_TYPE_SUITE, NAME_INCOME_TYPE, NAME_EDUCATION_TYPE, NAME_FAMILY_STATUS, NAME_HOUSING_TYPE,
    TRY_CAST(REGION_POPULATION_RELATIVE AS FLOAT), TRY_CAST(DAYS_BIRTH AS INT), TRY_CAST(DAYS_EMPLOYED AS INT), 
    TRY_CAST(DAYS_REGISTRATION AS FLOAT), TRY_CAST(DAYS_ID_PUBLISH AS INT), TRY_CAST(OWN_CAR_AGE AS FLOAT),
    TRY_CAST(FLAG_MOBIL AS INT), TRY_CAST(FLAG_EMP_PHONE AS INT), TRY_CAST(FLAG_WORK_PHONE AS INT), 
    TRY_CAST(FLAG_CONT_MOBILE AS INT), TRY_CAST(FLAG_PHONE AS INT), TRY_CAST(FLAG_EMAIL AS INT), 
    OCCUPATION_TYPE, TRY_CAST(CNT_FAM_MEMBERS AS FLOAT), TRY_CAST(REGION_RATING_CLIENT AS INT),
    TRY_CAST(REGION_RATING_CLIENT_W_CITY AS INT), WEEKDAY_APPR_PROCESS_START, 
    TRY_CAST(HOUR_APPR_PROCESS_START AS INT), TRY_CAST(REG_REGION_NOT_LIVE_REGION AS INT),
    TRY_CAST(REG_REGION_NOT_WORK_REGION AS INT), TRY_CAST(LIVE_REGION_NOT_WORK_REGION AS INT),
    TRY_CAST(REG_CITY_NOT_LIVE_CITY AS INT), TRY_CAST(REG_CITY_NOT_WORK_CITY AS INT),
    TRY_CAST(LIVE_CITY_NOT_WORK_CITY AS INT), ORGANIZATION_TYPE, TRY_CAST(EXT_SOURCE_1 AS FLOAT), 
    TRY_CAST(EXT_SOURCE_2 AS FLOAT), TRY_CAST(EXT_SOURCE_3 AS FLOAT), TRY_CAST(APARTMENTS_AVG AS FLOAT),
    TRY_CAST(BASEMENTAREA_AVG AS FLOAT), TRY_CAST(YEARS_BEGINEXPLUATATION_AVG AS FLOAT), 
    TRY_CAST(YEARS_BUILD_AVG AS FLOAT), TRY_CAST(COMMONAREA_AVG AS FLOAT), TRY_CAST(ELEVATORS_AVG AS FLOAT),
    TRY_CAST(ENTRANCES_AVG AS FLOAT), TRY_CAST(FLOORSMAX_AVG AS FLOAT), TRY_CAST(FLOORSMIN_AVG AS FLOAT),
    TRY_CAST(LANDAREA_AVG AS FLOAT), TRY_CAST(LIVINGAPARTMENTS_AVG AS FLOAT), TRY_CAST(LIVINGAREA_AVG AS FLOAT),
    TRY_CAST(NONLIVINGAPARTMENTS_AVG AS FLOAT), TRY_CAST(NONLIVINGAREA_AVG AS FLOAT), 
    TRY_CAST(APARTMENTS_MODE AS FLOAT), TRY_CAST(BASEMENTAREA_MODE AS FLOAT),
    TRY_CAST(YEARS_BEGINEXPLUATATION_MODE AS FLOAT), TRY_CAST(YEARS_BUILD_MODE AS FLOAT),
    TRY_CAST(COMMONAREA_MODE AS FLOAT), TRY_CAST(ELEVATORS_MODE AS FLOAT), TRY_CAST(ENTRANCES_MODE AS FLOAT),
    TRY_CAST(FLOORSMAX_MODE AS FLOAT), TRY_CAST(FLOORSMIN_MODE AS FLOAT), TRY_CAST(LANDAREA_MODE AS FLOAT),
    TRY_CAST(LIVINGAPARTMENTS_MODE AS FLOAT), TRY_CAST(LIVINGAREA_MODE AS FLOAT), 
    TRY_CAST(NONLIVINGAPARTMENTS_MODE AS FLOAT), TRY_CAST(NONLIVINGAREA_MODE AS FLOAT),
    TRY_CAST(APARTMENTS_MEDI AS FLOAT), TRY_CAST(BASEMENTAREA_MEDI AS FLOAT), 
    TRY_CAST(YEARS_BEGINEXPLUATATION_MEDI AS FLOAT), TRY_CAST(YEARS_BUILD_MEDI AS FLOAT), 
    TRY_CAST(COMMONAREA_MEDI AS FLOAT), TRY_CAST(ELEVATORS_MEDI AS FLOAT), 
    TRY_CAST(ENTRANCES_MEDI AS FLOAT), TRY_CAST(FLOORSMAX_MEDI AS FLOAT), TRY_CAST(FLOORSMIN_MEDI AS FLOAT),
    TRY_CAST(LANDAREA_MEDI AS FLOAT), TRY_CAST(LIVINGAPARTMENTS_MEDI AS FLOAT), 
    TRY_CAST(LIVINGAREA_MEDI AS FLOAT), TRY_CAST(NONLIVINGAPARTMENTS_MEDI AS FLOAT), 
    TRY_CAST(NONLIVINGAREA_MEDI AS FLOAT), FONDKAPREMONT_MODE, HOUSETYPE_MODE, 
    TRY_CAST(TOTALAREA_MODE AS FLOAT), WALLSMATERIAL_MODE, EMERGENCYSTATE_MODE, 
    TRY_CAST(OBS_30_CNT_SOCIAL_CIRCLE AS FLOAT), TRY_CAST(DEF_30_CNT_SOCIAL_CIRCLE AS FLOAT), 
    TRY_CAST(OBS_60_CNT_SOCIAL_CIRCLE AS FLOAT), TRY_CAST(DEF_60_CNT_SOCIAL_CIRCLE AS FLOAT), 
    TRY_CAST(DAYS_LAST_PHONE_CHANGE AS FLOAT), TRY_CAST(FLAG_DOCUMENT_2 AS INT), 
    TRY_CAST(FLAG_DOCUMENT_3 AS INT), TRY_CAST(FLAG_DOCUMENT_4 AS INT), TRY_CAST(FLAG_DOCUMENT_5 AS INT), 
    TRY_CAST(FLAG_DOCUMENT_6 AS INT), TRY_CAST(FLAG_DOCUMENT_7 AS INT), TRY_CAST(FLAG_DOCUMENT_8 AS INT), 
    TRY_CAST(FLAG_DOCUMENT_9 AS INT), TRY_CAST(FLAG_DOCUMENT_10 AS INT), TRY_CAST(FLAG_DOCUMENT_11 AS INT), 
    TRY_CAST(FLAG_DOCUMENT_12 AS INT), TRY_CAST(FLAG_DOCUMENT_13 AS INT), TRY_CAST(FLAG_DOCUMENT_14 AS INT),
    TRY_CAST(FLAG_DOCUMENT_15 AS INT), TRY_CAST(FLAG_DOCUMENT_16 AS INT), TRY_CAST(FLAG_DOCUMENT_17 AS INT), 
    TRY_CAST(FLAG_DOCUMENT_18 AS INT), TRY_CAST(FLAG_DOCUMENT_19 AS INT), TRY_CAST(FLAG_DOCUMENT_20 AS INT), 
    TRY_CAST(FLAG_DOCUMENT_21 AS INT), TRY_CAST(AMT_REQ_CREDIT_BUREAU_HOUR AS FLOAT), 
    TRY_CAST(AMT_REQ_CREDIT_BUREAU_DAY AS FLOAT), TRY_CAST(AMT_REQ_CREDIT_BUREAU_WEEK AS FLOAT), 
    TRY_CAST(AMT_REQ_CREDIT_BUREAU_MON AS FLOAT), TRY_CAST(AMT_REQ_CREDIT_BUREAU_QRT AS FLOAT), 
    TRY_CAST(AMT_REQ_CREDIT_BUREAU_YEAR AS FLOAT)
FROM application_train_staging;



SELECT TOP 100 
    SK_ID_CURR, 
    TARGET, 
    OCCUPATION_TYPE, 
    WALLSMATERIAL_MODE, 
    EMERGENCYSTATE_MODE 
FROM application_train_final;
