
-- atribuindo nvarchar para todas colunas para carregar os dados para tabela

drop table if exists previous_application

CREATE TABLE previous_application (
    SK_ID_PREV VARCHAR(MAX),
    SK_ID_CURR VARCHAR(MAX),
    NAME_CONTRACT_TYPE VARCHAR(MAX),
    AMT_ANNUITY VARCHAR(MAX),
    AMT_APPLICATION VARCHAR(MAX),
    AMT_CREDIT VARCHAR(MAX),
    AMT_DOWN_PAYMENT VARCHAR(MAX),
    AMT_GOODS_PRICE VARCHAR(MAX),
    WEEKDAY_APPR_PROCESS_START VARCHAR(MAX),
    HOUR_APPR_PROCESS_START VARCHAR(MAX),
    FLAG_LAST_APPL_PER_CONTRACT VARCHAR(MAX),
    NFLAG_LAST_APPL_IN_DAY VARCHAR(MAX),
    RATE_DOWN_PAYMENT VARCHAR(MAX),
    RATE_INTEREST_PRIMARY VARCHAR(MAX),
    RATE_INTEREST_PRIVILEGED VARCHAR(MAX),
    NAME_CASH_LOAN_PURPOSE VARCHAR(MAX),
    NAME_CONTRACT_STATUS VARCHAR(MAX),
    DAYS_DECISION VARCHAR(MAX),
    NAME_PAYMENT_TYPE VARCHAR(MAX),
    CODE_REJECT_REASON VARCHAR(MAX),
    NAME_TYPE_SUITE VARCHAR(MAX),
    NAME_CLIENT_TYPE VARCHAR(MAX),
    NAME_GOODS_CATEGORY VARCHAR(MAX),
    NAME_PORTFOLIO VARCHAR(MAX),
    NAME_PRODUCT_TYPE VARCHAR(MAX),
    CHANNEL_TYPE VARCHAR(MAX),
    SELLERPLACE_AREA VARCHAR(MAX), 
    NAME_SELLER_INDUSTRY VARCHAR(MAX),
    CNT_PAYMENT VARCHAR(MAX),
    NAME_YIELD_GROUP VARCHAR(MAX),
    PRODUCT_COMBINATION VARCHAR(MAX),
    DAYS_FIRST_DRAWING VARCHAR(MAX),
    DAYS_FIRST_DUE VARCHAR(MAX),
    DAYS_LAST_DUE_1ST_VERSION VARCHAR(MAX),
    DAYS_LAST_DUE VARCHAR(MAX),
    DAYS_TERMINATION VARCHAR(MAX),
    NFLAG_INSURED_ON_APPROVAL VARCHAR(MAX)
);


BULK INSERT previous_application
FROM 'D:\bd\Risco de Credito\previous_application.csv'
WITH (
   FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a',
    KEEPNULLS,
    TABLOCK
);
-- Cria uma nova tabela com os tipos certos

insert INTO previous_application_clean

SELECT
    -- Identificadores (Inteiros)
    TRY_CAST(SK_ID_PREV AS INT) AS SK_ID_PREV,
    TRY_CAST(SK_ID_CURR AS INT) AS SK_ID_CURR,

    -- Categorias (Texto)
    NAME_CONTRACT_TYPE,
    WEEKDAY_APPR_PROCESS_START,
    FLAG_LAST_APPL_PER_CONTRACT,
    NAME_CASH_LOAN_PURPOSE,
    NAME_CONTRACT_STATUS,
    NAME_PAYMENT_TYPE,
    CODE_REJECT_REASON,
    NAME_TYPE_SUITE,
    NAME_CLIENT_TYPE,
    NAME_GOODS_CATEGORY,
    NAME_PORTFOLIO,
    NAME_PRODUCT_TYPE,
    CHANNEL_TYPE,
    NAME_SELLER_INDUSTRY,
    NAME_YIELD_GROUP,
    PRODUCT_COMBINATION,

    -- Valores Financeiros (Float/Decimal)
    TRY_CAST(AMT_ANNUITY AS FLOAT) AS AMT_ANNUITY,
    TRY_CAST(AMT_APPLICATION AS FLOAT) AS AMT_APPLICATION,
    TRY_CAST(AMT_CREDIT AS FLOAT) AS AMT_CREDIT,
    TRY_CAST(AMT_DOWN_PAYMENT AS FLOAT) AS AMT_DOWN_PAYMENT,
    TRY_CAST(AMT_GOODS_PRICE AS FLOAT) AS AMT_GOODS_PRICE,
    TRY_CAST(RATE_DOWN_PAYMENT AS FLOAT) AS RATE_DOWN_PAYMENT,
    TRY_CAST(RATE_INTEREST_PRIMARY AS FLOAT) AS RATE_INTEREST_PRIMARY,
    TRY_CAST(RATE_INTEREST_PRIVILEGED AS FLOAT) AS RATE_INTEREST_PRIVILEGED,

    -- Métricas e Contagem
    TRY_CAST(HOUR_APPR_PROCESS_START AS INT) AS HOUR_APPR_PROCESS_START,
    TRY_CAST(NFLAG_LAST_APPL_IN_DAY AS INT) AS NFLAG_LAST_APPL_IN_DAY,
    TRY_CAST(SELLERPLACE_AREA AS FLOAT) AS SELLERPLACE_AREA, -- Resolvido!
    TRY_CAST(CNT_PAYMENT AS FLOAT) AS CNT_PAYMENT,
    TRY_CAST(NFLAG_INSURED_ON_APPROVAL AS FLOAT) AS NFLAG_INSURED_ON_APPROVAL,

    -- Dias (Inteiros Relativos)
    TRY_CAST(DAYS_DECISION AS INT) AS DAYS_DECISION,
    TRY_CAST(DAYS_FIRST_DRAWING AS FLOAT) AS DAYS_FIRST_DRAWING,
    TRY_CAST(DAYS_FIRST_DUE AS FLOAT) AS DAYS_FIRST_DUE,
    TRY_CAST(DAYS_LAST_DUE_1ST_VERSION AS FLOAT) AS DAYS_LAST_DUE_1ST_VERSION,
    TRY_CAST(DAYS_LAST_DUE AS FLOAT) AS DAYS_LAST_DUE,
    TRY_CAST(DAYS_TERMINATION AS FLOAT) AS DAYS_TERMINATION

FROM previous_application

truncate table previous_application

select top 1000 * from previous_application_clean 
