--tabela de agregação dos contratos anteriores do clientes na instituição, desconsiderando os outliers
select 

 [SK_ID_PREV]
,[SK_ID_CURR]
,[AMT_APPLICATION]
,[AMT_CREDIT]
,([AMT_CREDIT]-[AMT_APPLICATION]) difcredito
,NAME_CONTRACT_TYPE
,CNT_PAYMENT
,[NAME_CONTRACT_STATUS]
,[NAME_PRODUCT_TYPE]
,[NAME_YIELD_GROUP]
,[NAME_PORTFOLIO]
,case when [AMT_APPLICATION]>0 then ([AMT_CREDIT]/[AMT_APPLICATION]) else 0 end as pcaprovado
,case when [DAYS_FIRST_DRAWING]=365243 then null else [DAYS_FIRST_DRAWING] end as [DAYS_FIRST_DRAWING]
,case when [DAYS_FIRST_DUE]=365243 then null else [DAYS_FIRST_DUE] end as [DAYS_FIRST_DUE]
,CASE WHEN DAYS_LAST_DUE_1ST_VERSION = 365243 THEN NULL ELSE DAYS_LAST_DUE_1ST_VERSION END AS DAYS_LAST_DUE_1ST_VERSION
,CASE WHEN DAYS_LAST_DUE = 365243 THEN NULL ELSE DAYS_LAST_DUE END AS DAYS_LAST_DUE
,CASE WHEN DAYS_TERMINATION = 365243 THEN NULL ELSE DAYS_TERMINATION END AS DAYS_TERMINATION

INTO [agreg_previous_application]

from previous_application_clean
where AMT_CREDIT<=1515377.70 or AMT_CREDIT is null
